services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ledgerflow
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ledgerflow_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
