class Accounting::JournalEntry < ApplicationRecord
  self.table_name = "accounting_journal_entries"

  # source_type of the entry that settles the income accounts when a fiscal year is closed (Accounting::CloseFiscalYear).
  CLOSING_SOURCE = "Accounting::ClosingEntry".freeze
  # source_type of the entries created by Accounting::ImportOpeningBalances.
  OPENING_SOURCE = "Accounting::OpeningBalance".freeze

  # source_type of the draft proposed by Fx::Revalue (unrealized exchange differences, its reversal scheduled for the next day).
  REVALUATION_SOURCE = "Accounting::Revaluation".freeze

  # source_type of the opening entry of a year, made by the closing of the year before (F10): the closing balances of classes 0 to 5, the open lines of the partners
  # one by one.
  CARRY_FORWARD_SOURCE = "Accounting::CarryForward".freeze

  # source_type of the exchange difference a lettering generates (F11): posted by itself, linked to the lettering, undone with it.
  FX_SOURCE = "Accounting::FxAdjustment".freeze

  # The entries that count in the ledger and its reports: validated ones, including those since reversed (the reversal, also validated, cancels
  # them). Reports that read VAT codes, analytical annotations or projects keep to `posted`: a reversal does not copy those.
  LEDGER_STATUSES = %i[posted reversed].freeze

  acts_as_tenant :entity
  broadcasts_refreshes_to ->(r) { [ r.entity, :journal_entries ] }

  include Accounting::Statusable
  include Accounting::Immutable
  include Accounting::Auditable
  include Accounting::AuditTrailed

  belongs_to :journal,     class_name: "Accounting::Journal"
  belongs_to :fiscal_year, class_name: "Accounting::FiscalYear"
  belongs_to :reversal_of, class_name: "Accounting::JournalEntry", optional: true
  belongs_to :lettering,   class_name: "Accounting::Lettering", optional: true # the lettering that generated this entry (an exchange difference)
  # Who wrote the draft by hand; nil for entries generated by the system (invoices, closing, imports).
  belongs_to :created_by,  class_name: "User", optional: true
  has_one    :reversal,    class_name: "Accounting::JournalEntry", foreign_key: :reversal_of_id, inverse_of: :reversal_of
  has_many   :lines,       class_name: "Accounting::JournalEntryLine",
                           foreign_key: :journal_entry_id,
                           inverse_of: :journal_entry,
                           dependent: :destroy

  accepts_nested_attributes_for :lines, allow_destroy: true,
    reject_if: proc { |attrs| attrs["account_id"].blank? }

  autofilter_column :reference,  sql: "accounting_journal_entries.reference", type: :string
  autofilter_column :journal,    sql: "accounting_journals.code", type: :string, joins: :journal
  autofilter_column :entry_date, sql: "accounting_journal_entries.entry_date", type: :date
  autofilter_column :status,     sql: "accounting_journal_entries.status", type: :enum

  validates :entry_date, presence: true
  validates :reference,  presence: true, unless: :draft?
  validates :reference,  uniqueness: { scope: :entity_id, case_sensitive: false }, allow_nil: true

  scope :for_fiscal_year, ->(fy) { where(fiscal_year: fy) }

  def self.filter_by(q)
    matching(status: q[:status], journal_id: q[:journal_id], fiscal_year_id: q[:fiscal_year_id])
      .search(q[:q], "reference", "description")
      .between(:entry_date, q[:from], q[:to])
  end

  # Four-eyes (F01): the author of a manual entry may not validate it when the entity requires a second person,
  # from the entity's threshold upward (no threshold: always).
  def four_eyes_blocks?(user)
    return false unless user && created_by_id == user.id && entity.four_eyes?

    entity.four_eyes_threshold.nil? || lines.sum(:debit) >= entity.four_eyes_threshold
  end

  # Posting and reversal are logged by their services (post_entry, reverse_entry): one audit row per action.
  def self.ledger_status_values = LEDGER_STATUSES.map { |s| statuses.fetch(s) }

  scope :in_ledger, -> { where(status: ledger_status_values) }

  # The entry that books the rate difference of a lettering: the one `PostFxAdjustment` generates, or a deposit's own (same description).
  def fx_adjustment? = source_type == FX_SOURCE || description.to_s.start_with?("FX adjustment")

  def in_ledger? = LEDGER_STATUSES.include?(status.to_sym)

  def skip_audit? = saved_change_to_status? && status.to_s.in?(%w[posted reversed])
end
