# The realized exchange difference of a lettering in a foreign currency (F11). The lines cancel out in their currency but not in EUR when the rate moved
# between the invoice and the payment: the difference is booked on the exchange difference account (loss or gain, the entity's) and a line on the
# trade account tops the group up, so that the lettering balances in EUR too.
#
# The entry is generated by the lettering: dated at its latest line, in the open period (a locked one refuses the lettering, with the date), source
# Accounting::JournalEntry::FX_SOURCE, posted by itself unless the entity keeps it as a draft (`fx_realized_as_draft`: then its trade line joins the
# lettering when it is posted, Actions::FinalizeFxAdjustment). Linked to the lettering by Actions::LinkFxAdjustment, which undoing the lettering reads.
class Accounting::Actions::PostFxAdjustment
  extend LightService::Action

  expects  :lines
  promises :lines

  executed do |ctx|
    lines = ctx.lines
    ctx.lines = lines
    next unless lines.any? { |l| l.currency != "EUR" && !l.journal_entry.fx_adjustment? }

    diff = lines.sum(&:credit) - lines.sum(&:debit)
    next if diff.zero?

    latest  = lines.max_by { |l| l.journal_entry.entry_date }
    date    = latest.journal_entry.entry_date
    gain    = diff.positive?
    entity  = latest.entity
    account = Accounting::Account.find_by(code: gain ? entity.fx_gain_account_code : entity.fx_loss_account_code)
    journal = Accounting::Journal.where(journal_type: :misc, active: true).first

    problem = if Accounting::PeriodLock.covering(date).exists?
      "The exchange difference of this lettering (#{diff.abs.to_s('F')} EUR) would be dated #{Accounting::DatePresenter.new(date).format}, in a locked period: unlock it or letter later lines."
    elsif account.nil?
      "The exchange difference account #{gain ? entity.fx_gain_account_code : entity.fx_loss_account_code} does not exist: create it (Settings > Chart of accounts)."
    elsif journal.nil?
      "No active misc journal found for the FX adjustment entry."
    end
    next ctx.fail_with_rollback!(problem) if problem

    entry = Accounting::JournalEntry.new(journal: journal, fiscal_year: latest.journal_entry.fiscal_year, entry_date: date, status: :draft,
                                         source_type: Accounting::JournalEntry::FX_SOURCE, description: "FX adjustment — #{latest.account.code}")
    entry.reference = journal.next_sequence_number(year: date.year)
    entry.save!

    ApplicationRecord.connection.execute("SET CONSTRAINTS enforce_double_entry DEFERRED")
    amount     = diff.abs
    zero       = BigDecimal("0")
    trade_line = Accounting::JournalEntryLine.create!(journal_entry: entry, account: latest.account, partner: latest.partner, label: "FX adjustment",
                                                      debit: gain ? amount : zero, credit: gain ? zero : amount)
    Accounting::JournalEntryLine.create!(journal_entry: entry, account: account, label: "FX adjustment",
                                         debit: gain ? zero : amount, credit: gain ? amount : zero)

    ctx[:fx_entry] = entry
    next if entity.fx_realized_as_draft # posted by a person later; its trade line then joins the lettering

    Accounting::PostJournalEntry.call!(entry: entry, keep_reference: true)
    ctx.lines = lines + [ trade_line ]
  rescue ActiveRecord::RecordInvalid, Accounting::PostRefused => e
    ctx.fail_with_rollback!("FX adjustment error: #{e.message}")
  end
end
