class Accounting::ReportPolicy < ApplicationPolicy
  def trial_balance?    = entity_manager?
  def balance_sheet?    = trial_balance?
  def income_statement? = trial_balance?
  def annual_accounts?  = trial_balance?
  def general_ledger?   = trial_balance?
  def aged_balance?     = trial_balance?
  def unlettered_lines? = trial_balance?
  def annual_customer_listing? = trial_balance?
  def cash_forecast? = trial_balance?
  def cash_flow? = trial_balance?
  def fixed_asset_movements? = trial_balance?
  def bank_reconciliation_report? = trial_balance?
  def analytic_by_project? = trial_balance?
  def analytic_by_axis?    = trial_balance?
  def analytic_cross?      = trial_balance?
  def analytic_pivot?      = trial_balance?
  def analytic_margin?     = trial_balance?
end
